import os

import time

import pyautogui
screenWidth, screenHeight = pyautogui.size()

print('AUTO CANE FARMER USE 327 SPEED AND KEYBIND LEFT CLICK TO SPACE FARM MUST BE BUILT CORRECTLY')
time.sleep(2)
print ('STARTING IN 10')
time.sleep(1)
print ('STARTING IN 9')
time.sleep(1)
print ('STARTING IN 8')
time.sleep(1)
print ('STARTING IN 7')
time.sleep(1)
print ('STARTING IN 6')
time.sleep(1)
print ('STARTING IN 5')
time.sleep(1)
print ('STARTING IN 4')
time.sleep(1)
print ('STARTING IN 3')
time.sleep(1)
print ('STARTING IN 2')
time.sleep(1)
print ('STARTING IN 1')
time.sleep(1)
print ('STARTING NOW...')


x = 1
while x == 1:
    pyautogui.keyDown('a') , pyautogui.keyDown('space')
    time.sleep(18)
    print('ROW 1 DONE')
    pyautogui.keyUp('a') , pyautogui.keyUp('space')
    time.sleep(1)
    pyautogui.keyDown('s') , pyautogui.keyDown('space')
    time.sleep(18)
    print('ROW 2 DONE')
    pyautogui.keyUp('s') , pyautogui.keyUp('space')
    time.sleep(1)
    pyautogui.keyDown('a') , pyautogui.keyDown('space')
    time.sleep(18)
    print('ROW 3 DONE')
    pyautogui.keyUp('a') , pyautogui.keyUp('space')
    time.sleep(1)
    pyautogui.keyDown('s') , pyautogui.keyDown('space')
    time.sleep(18)
    print('ROW 4 DONE')
    pyautogui.keyUp('s') , pyautogui.keyUp('space')
    time.sleep(1)
    pyautogui.keyDown('a') , pyautogui.keyDown('space')
    time.sleep(18)
    print('ROW 5 DONE')
    pyautogui.keyUp('a') , pyautogui.keyUp('space')
    time.sleep(1)
    pyautogui.keyDown('s') , pyautogui.keyDown('space')
    time.sleep(18)
    print('ROW 6 DONE')
    pyautogui.keyUp('s') , pyautogui.keyUp('space')
    time.sleep(1)
    pyautogui.keyDown('a') , pyautogui.keyDown('space')
    time.sleep(18)
    print('ROW 7 DONE')
    pyautogui.keyUp('a') , pyautogui.keyUp('space')
    time.sleep(1)
    pyautogui.keyDown('s') , pyautogui.keyDown('space')
    time.sleep(18)
    print('ROW 8 DONE')
    pyautogui.keyUp('s') , pyautogui.keyUp('space')
    time.sleep(1)
    pyautogui.keyDown('a') , pyautogui.keyDown('space')
    time.sleep(18)
    print('ROW 9 DONE')
    pyautogui.keyUp('a') , pyautogui.keyUp('space')
    time.sleep(1)
    pyautogui.keyDown('s') , pyautogui.keyDown('space')
    time.sleep(18)
    print('ROW 10 DONE')
    pyautogui.keyUp('s') , pyautogui.keyUp('space')
    time.sleep(1)
    pyautogui.keyDown('a') , pyautogui.keyDown('space')
    time.sleep(18)
    print('ROW 11 DONE')
    pyautogui.keyUp('a') , pyautogui.keyUp('space')
    time.sleep(1)
    pyautogui.keyDown('s') , pyautogui.keyDown('space')
    time.sleep(18)
    print('ROW 12 DONE')
    pyautogui.keyUp('s') , pyautogui.keyUp('space')
    time.sleep(1)
    pyautogui.keyDown('a') , pyautogui.keyDown('space')
    time.sleep(18)
    print('ROW 13 DONE')
    pyautogui.keyUp('a') , pyautogui.keyUp('space')
    time.sleep(1)
    pyautogui.keyDown('s') , pyautogui.keyDown('space')
    time.sleep(18)
    print('ROW 14 DONE')
    pyautogui.keyUp('s') , pyautogui.keyUp('space')
    time.sleep(1)
    pyautogui.keyDown('a') , pyautogui.keyDown('space')
    time.sleep(18)
    print('ROW 15 DONE')
    pyautogui.keyUp('a') , pyautogui.keyUp('space')
    time.sleep(1)
    pyautogui.keyDown('s') , pyautogui.keyDown('space')
    time.sleep(18)
    print('ROW 16 DONE')
    pyautogui.keyUp('s') , pyautogui.keyUp('space')
    time.sleep(1)
    pyautogui.keyDown('a') , pyautogui.keyDown('space')
    time.sleep(18)
    print('ROW 17 DONE')
    pyautogui.keyUp('a') , pyautogui.keyUp('space')
    time.sleep(1)
    pyautogui.keyDown('s') , pyautogui.keyDown('space')
    time.sleep(18)
    print('ROW 18 DONE')
    pyautogui.keyUp('s') , pyautogui.keyUp('space')
    time.sleep(1)
    pyautogui.keyDown('a') , pyautogui.keyDown('space')
    time.sleep(18)
    print('ROW 19 DONE')
    pyautogui.keyUp('a') , pyautogui.keyUp('space')
    time.sleep(1)
    pyautogui.keyDown('s') , pyautogui.keyDown('space')
    time.sleep(18)
    print('ROW 20 DONE')
    pyautogui.keyUp('s') , pyautogui.keyUp('space')
    time.sleep(1)
    pyautogui.keyDown('a') , pyautogui.keyDown('space')
    time.sleep(18)
    print('ROW 21 DONE')
    pyautogui.keyUp('a') , pyautogui.keyUp('space')
    time.sleep(1)
    pyautogui.keyDown('s') , pyautogui.keyDown('space')
    time.sleep(18)
    print('ROW 22 DONE')
    pyautogui.keyUp('s') , pyautogui.keyUp('space')
    time.sleep(1)
    pyautogui.keyDown('a') , pyautogui.keyDown('space')
    time.sleep(18)
    print('ROW 23 DONE')
    pyautogui.keyUp('a') , pyautogui.keyUp('space')
    time.sleep(1)
    pyautogui.keyDown('s') , pyautogui.keyDown('space')
    time.sleep(18)
    print('ROW 24 DONE')
    pyautogui.keyUp('s') , pyautogui.keyUp('space')
    time.sleep(1)
    pyautogui.keyDown('a') , pyautogui.keyDown('space')
    time.sleep(18)
    print('ROW 25 DONE')
    pyautogui.keyUp('a') , pyautogui.keyUp('space')
    time.sleep(1)
    pyautogui.keyDown('s') , pyautogui.keyDown('space')
    time.sleep(18)
    print('ROW 26 DONE')
    pyautogui.keyUp('s') , pyautogui.keyUp('space')
    time.sleep(1)
    pyautogui.keyDown('a') , pyautogui.keyDown('space')
    time.sleep(18)
    print('ROW 27 DONE')
    pyautogui.keyUp('a') , pyautogui.keyUp('space')
    time.sleep(1)
    pyautogui.keyDown('s') , pyautogui.keyDown('space')
    time.sleep(18)
    print('ROW 28 DONE')
    pyautogui.keyUp('s') , pyautogui.keyUp('space')
    time.sleep(1)
    pyautogui.keyDown('a') , pyautogui.keyDown('space')
    time.sleep(18)
    print('ROW 29 DONE')
    pyautogui.keyUp('a') , pyautogui.keyUp('space')
    time.sleep(1)
    pyautogui.keyDown('s') , pyautogui.keyDown('space')
    time.sleep(18)
    print('ROW 30 DONE')
    pyautogui.keyUp('s') , pyautogui.keyUp('space')
    time.sleep(1)
    pyautogui.keyDown('a') , pyautogui.keyDown('space')
    time.sleep(18)
    print('ROW 31 DONE')
    pyautogui.keyUp('a') , pyautogui.keyUp('space')
    time.sleep(1)
    pyautogui.keyDown('s') , pyautogui.keyDown('space')
    time.sleep(18)
    print('ROW 32 DONE')
    pyautogui.keyUp('s') , pyautogui.keyUp('space')
    time.sleep(1)
    pyautogui.keyDown('a') , pyautogui.keyDown('space')
    time.sleep(18)
    print('ROW 33 DONE')
    pyautogui.keyUp('a') , pyautogui.keyUp('space')
    time.sleep(1)
    pyautogui.keyDown('s') , pyautogui.keyDown('space')
    time.sleep(18)
    print('ROW 34 DONE')
    pyautogui.keyUp('s') , pyautogui.keyUp('space')
    time.sleep(1)
    pyautogui.keyDown('a') , pyautogui.keyDown('space')
    time.sleep(18)
    print('ROW 35 DONE')
    pyautogui.keyUp('a') , pyautogui.keyUp('space')
    time.sleep(1)
    pyautogui.keyDown('s') , pyautogui.keyDown('space')
    time.sleep(18)
    print('ROW 36 DONE')
    pyautogui.keyUp('s') , pyautogui.keyUp('space')
    time.sleep(1)
    pyautogui.keyDown('a') , pyautogui.keyDown('space')
    time.sleep(18)
    print('ROW 37 DONE')
    pyautogui.keyUp('a') , pyautogui.keyUp('space')
    time.sleep(1)
    pyautogui.keyDown('s') , pyautogui.keyDown('space')
    time.sleep(18)
    print('ROW 38 DONE')
    pyautogui.keyUp('s') , pyautogui.keyUp('space')
    time.sleep(1)
    pyautogui.keyDown('a') , pyautogui.keyDown('space')
    time.sleep(18)
    print('ROW 39 DONE')
    pyautogui.keyUp('a') , pyautogui.keyUp('space')
    time.sleep(1)
    pyautogui.keyDown('s') , pyautogui.keyDown('space')
    time.sleep(18)
    print('ROW 40 DONE')
    pyautogui.keyUp('s') , pyautogui.keyUp('space')
    time.sleep(1)
    pyautogui.keyDown('a') , pyautogui.keyDown('space')
    time.sleep(18)
    print('ROW 41 DONE')
    pyautogui.keyUp('a') , pyautogui.keyUp('space')
    time.sleep(1)
    pyautogui.keyDown('s') , pyautogui.keyDown('space')
    time.sleep(18)
    print('ROW 42 DONE')
    pyautogui.keyUp('s') , pyautogui.keyUp('space')
    time.sleep(1)
    pyautogui.keyDown('a') , pyautogui.keyDown('space')
    time.sleep(18)
    print('ROW 43 DONE')
    pyautogui.keyUp('a') , pyautogui.keyUp('space')
    time.sleep(1)
    pyautogui.keyDown('s') , pyautogui.keyDown('space')
    time.sleep(18)
    print('ROW 44 DONE')
    pyautogui.keyUp('s') , pyautogui.keyUp('space')
    time.sleep(1)
    pyautogui.keyDown('a') , pyautogui.keyDown('space')
    time.sleep(18)
    print('ROW 45 DONE')
    pyautogui.keyUp('a') , pyautogui.keyUp('space')
    time.sleep(1)
    pyautogui.keyDown('s') , pyautogui.keyDown('space')
    time.sleep(18)
    print('ROW 46 DONE')
    pyautogui.keyUp('s') , pyautogui.keyUp('space')
    time.sleep(1)
    pyautogui.keyDown('a') , pyautogui.keyDown('space')
    time.sleep(18)
    print('ROW 47 DONE')
    pyautogui.keyUp('a') , pyautogui.keyUp('space')
    time.sleep(1)
    pyautogui.keyDown('s') , pyautogui.keyDown('space')
    time.sleep(18)
    print('ROW 48 DONE')
    pyautogui.keyUp('s') , pyautogui.keyUp('space')
    time.sleep(1)
    pyautogui.keyDown('a') , pyautogui.keyDown('space')
    time.sleep(18)
    print('ROW 49 DONE')
    pyautogui.keyUp('a') , pyautogui.keyUp('space')
    time.sleep(1)
    pyautogui.keyDown('s') , pyautogui.keyDown('space')
    time.sleep(18)
    print('ROW 50 DONE')
    pyautogui.keyUp('s') , pyautogui.keyUp('space')
    time.sleep(1)
    pyautogui.keyDown('a') , pyautogui.keyDown('space')
    time.sleep(18)
    print('ROW 51 DONE')
    pyautogui.keyUp('a') , pyautogui.keyUp('space')
    time.sleep(1)
    pyautogui.keyDown('s') , pyautogui.keyDown('space')
    time.sleep(18)
    print('ROW 52 DONE')
    pyautogui.keyUp('s') , pyautogui.keyUp('space')
    time.sleep(1)
    pyautogui.keyDown('a') , pyautogui.keyDown('space')
    time.sleep(18)
    pyautogui.keyUp('a') , pyautogui.keyUp('space')
    time.sleep(1)
    print('LAYER COMPLETE')
    time.sleep(1)
    print('TROUBLESHOOTING BUG.')
    time.sleep(.5)
    print('TROUBLESHOOTING BUG..')
    time.sleep(.5)
    print('TROUBLESHOOTING BUG...')
    time.sleep(.5)
    print('TROUBLESHOOTING COMPLETE')
    time.sleep(.1)
    print('FIXING BUG...')
    pyautogui.keyDown('a')
    time.sleep(2)
    pyautogui.keyUp('a')
    print('BUG FIXED')
    time.sleep(.3)
    print('CONTINUING NORMAL PROCEDURE')